/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 are:
	1, 2, 3, 5, 8, 13, 21, 35, 55, 89, ...

By considering the terms in the Fib sequence whose values do not exceed four million, find the sum of the even valued terms.
*/

#include <iostream>
#include <cstdio>
using namespace std;

int main(){
	int sum = 0;
	int current = 1;
	int last = 1;

	while(current < 4000000){
		int temp = last;
		last = current;
		current = current+temp;
		if(current % 2 == 0) sum += current;
		
	}
	cout << sum << endl;
}
